%REM CLEAN LOG AND GENERATE LATEST DATABASE DIRECTORIES

%PURGE MSZHZ.TEMPCON1
%PURGE MSZHZ.TEMPARC1
%PURGE MSZHZ.TEMPDEV1
%PURGE MSZHZ.TEMPPRD1


%LLIB TSCONT.********,MSZHZ.TEMPCON1
%LLIB TSARCH.********,MSZHZ.TEMPARC1
%LLIB TSDVLP.********,MSZHZ.TEMPDEV1
%LLIB TSPROD.********,MSZHZ.TEMPPRD1
%LET JOBID=A00
%LET GO=YES
%JCLSETUP: %CREATE 1,1
%/&$USERID&JOBID JOB 1910-0000-1000,TIME=(0,55),REGION=6000K,
%/    MSGLEVEL=(0,0),MSGCLASS=R,NOTIFY=&$USERID
%*JOBPARM LINES=999
%/*
%/SAS   EXEC SAS,OPTIONS='CAPSOUT DQUOTE LS=132',
%/      WORK='100,80',REGION=6M
%/FT22F001 DD   SYSOUT=*
%/*
%/SYSOUT   DD DUMMY
%/SYSIN    DD *
%SET        TEMPORARY,NOCOMMAND

%/RELEASE EXEC PGM=RELJOB,PARM=&$USERID.C0K,COND=(0,NE)
%ENDS
