$PURGE MSZHZ.COPYPROD
LLIB TSPROD.********,MSZHZ.COPYPROD
%LET JOBID=PRD
%LET GO=YES
%JCLSETUP: %CREATE 1,1
%/&$USERID&JOBID JOB 1910-0000-1000,TIME=(0,05),REGION=6000K,
%/    MSGLEVEL=(1,1),MSGCLASS=R,NOTIFY=&$USERID
%*JOBPARM LINES=999
%/*
%/SAS   EXEC SAS,OPTIONS='CAPSOUT DQUOTE LS=132',
%/      WORK='10,10',REGION=6M
%/FT22F001 DD   SYSOUT=*
%/*
%/SYSOUT   DD DUMMY
%/SYSIN    DD *
%SET        TEMPORARY,NOCOMMAND









%/RELEASE EXEC PGM=RELJOB,PARM=&$USERID.VKY,COND=(0,NE)
%ENDS
