%LET JOBID=VKY,GO=YES
%JCLSETUP: %CREATE 1,1
%PARSE   DATE,&$DATE
%LET YY=&$1
%LET MM=&$2
%LET DD=&$3
%LET SDATE=&DD-&MM-&YY
%LET TRY=&MM&DD&YY
%LET TDATE=&MM/&DD/&YY
%/&$USERID&JOBID JOB 1910-0000-1000,TIME=(0,20),REGION=6M,TYPRUN=HOLD,
%/    MSGLEVEL=(1,1),MSGCLASS=R,NOTIFY=&$USERID
/*JOBPARM LINES=999
%/*
%/SCRUNC   EXEC SERV
OPT,NOSETRC,NOERROR
SCR,,MSZHZ.TSPROD.CHKLIST
%/*
%/MAKE EXEC GUTSUTIL,CONTROL='$'
%/SYSPUNCH DD DSN=&&TEMPL,
%/      DCB=(LRECL=240,BLKSIZE=23280,RECFM=FB),
%/       SPACE=(TRK,(10,10),RLSE),
%/      UNIT=SYSSQ,DISP=(NEW,PASS,DELETE)
%/SYSIN DD *
$PUNCH  MSZHZ.LISTTSP
%/*
%/MAKE EXEC GUTSUTIL,CONTROL='$'
%/SYSPUNCH DD DSN=&&TEMPP,
%/      DCB=(LRECL=240,BLKSIZE=23280,RECFM=FB),
%/       SPACE=(TRK,(10,10),RLSE),
%/      UNIT=SYSSQ,DISP=(NEW,PASS,DELETE)
%/SYSIN DD *
$PUNCH  MSZHZ.COPYPROD
%/*
%/SAS   EXEC SAS,OPTIONS='EMAILHOST=SMTP.INFORES.COM',
%/      WORK='1200,600',REGION=6M
%/FT22F001 DD   SYSOUT=*
%/*
%/GUTSOUTC DD SYSOUT=(F,&$USERID),DEST=GUTS,DSN=&&CHKPR2CN
%/GUTSFIL1 DD SYSOUT=(F,&$USERID),DEST=GUTS,DSN=&&FILEONE
%/SECFIL1  DD SYSOUT=(F,&$USERID),DEST=GUTS,DSN=&&SECOONE
%/NEWLIST  DD SYSOUT=(F,&$USERID),DEST=GUTS,DSN=&&LISTTSP
%/*
%/LSTPROD  DD DSN=&&TEMPL,DISP=(OLD,DELETE)
%/NEWPROD  DD DSN=&&TEMPP,DISP=(OLD,DELETE)
%/ORIGOUT  DD DSN=MSZHZ.TSPROD.CHKLIST,
%/         DISP=(NEW,CATLG,DELETE),UNIT=USR,SPACE=(TRK,(20,20),RLSE),
%/         DCB=(LRECL=60,BLKSIZE=8880,RECFM=FB)
%/*
%/SYSOUT   DD DUMMY
%/SYSIN DD *
%SET        TEMPORARY,NOCOMMAND

 OPTIONS NOCENTER MLOGIC SYMBOLGEN MPRINT;

   %MACRO READFILE(FILE=);

 DATA &&FILE;
  INFILE &&FILE DLM='*' DSD ;
  INPUT  @4 TOOLNAM :$17.
  ;
  TNAME=SUBSTR(TOOLNAM,8,8);
 RUN;
PROC PRINT DATA =&&FILE (OBS=5);
 PROC SORT;
  BY TNAME;

   %MEND READFILE;

     %READFILE(FILE=LSTPROD);
     %READFILE(FILE=NEWPROD);



DATA COMMON NEW_ENTRIES;
 MERGE LSTPROD(IN=A) NEWPROD (IN=B);
 BY TNAME;
 IF A AND NOT B THEN OUTPUT COMMON ;
 IF B AND NOT A THEN OUTPUT NEW_ENTRIES ;
RUN;

PROC PRINT DATA=NEW_ENTRIES (OBS=10);
 TITLE 'NEW ENTRIES';

PROC SQL;
  SELECT COUNT(*) INTO: TOT_NEW FROM NEW_ENTRIES;
  SELECT COUNT(*) INTO: COUNTLST FROM LSTPROD ;
  SELECT COUNT(*) INTO: TOT_REM FROM COMMON;
  SELECT COUNT(*) INTO: COUNTNEW FROM NEWPROD ;
  SELECT TOOLNAM INTO: NEW_TOL SEPARATED BY "," FROM NEW_ENTRIES;
  SELECT TOOLNAM INTO: REM_TOL SEPARATED BY "," FROM COMMON;
QUIT;

   %MACRO CHKIT;
      %IF &&TOT_NEW>0 %THEN %DO;
     DATA _NULL_;
       FILE NEWLIST  NOTITLES ;
       SET NEWPROD  ;
      PUT
       @4 TOOLNAM :$17.;
      RUN;
     %END;
  %MEND;
     %CHKIT;

        %MACRO LOOP2;

PROC SORT DATA=NEW_ENTRIES;
BY TOOLNAM;


DATA NEW_ENTRIES;
 SET NEW_ENTRIES;
   %DO I=1 %TO &&TOT_NEW ;
    K=&&I;
   %END;
RUN;

PROC PRINT DATA=NEW_ENTRIES;
 TITLE " DO LOOP";








      /*   LIST OF NEW TOOLS */
DATA _NULL_;
 SET NEW_ENTRIES;
 FILE ORIGOUT  NOTITLES;
   PUT @1 TOOLNAM $14.;
RUN;

         /*  TO CREATE THE FILEONE AND SECOONE GUTS FILES  */
PROC SQL NOPRINT;
 SELECT COUNT(*) INTO: COUNTPRD FROM NEW_ENTRIES;
QUIT;
       /*  TO CREATE THE GUTS MACRO VARIABLES */

DATA FIRSTLST (KEEP=SUBM);
 SET NEW_ENTRIES;
 HEADER='%IF ';
 NUMR=" "||"I="|| TRIM(LEFT(&&COUNTLST+_N_))  ;
 ASSG=' %LET NAME=';
 SUBM=
HEADER||TRIM(NUMR)||TRIM(ASSG)||TRIM(TOOLNAM);
RUN;


      /*   CREATE MACRO VARIABLES TO INSERT  */


DATA SECLST      (KEEP=SECOND);
 SET NEW_ENTRIES;
  PART1='%LET TEST'||TRIM(LEFT((&&COUNTLST+_N_)));
  PART2="="||"TEST"||TRIM(LEFT((&&COUNTLST+_N_)))||";"  ;
  SECOND=TRIM(PART1)||TRIM(PART2);
RUN;



DATA _NULL_;
 FILE GUTSFIL1 NOTITLES ;
 SET FIRSTLST ;
  PUT
  @1 SUBM  $45.;
RUN;


DATA _NULL_;
 FILE SECFIL1 NOTITLES;
 SET SECLST ;
  PUT
  @1 SECOND $45.;
RUN;


    %MEND;

     %MACRO MYMAC1;
       %LET TOLIST1="Orion@*******.com";
       %LET TOLIST=&&TOLIST1;

          FILENAME MYMAIL EMAIL TO=(&&TOLIST)
           SUBJECT="DIRECTORY UPDATED MAIL - II";
DATA _NULL_;
  FILE MYMAIL;
PUT 'HI, ';
PUT ' ';
PUT ' THE BELOW IS THE WEEKLY REPORT STATUS OF     ';
PUT '           NEW TOOLS IN THE TSPROD DIRECTORIES';
PUT ' ';
PUT " THERE ARE &&COUNTNEW TOOLS IN TSPROD DIRECTORY AS ON &SDATE";
PUT ' ';
PUT "NUMBER OF NEW TSPROD TOOLS ARE : &&TOT_NEW   ";
PUT ' ';
PUT "The below mentioned are the list of tools added to TSPROD";
PUT ' ';
PUT "&&NEW_TOL";
PUT ' ';
PUT "NUMBER OF REMOVED TSPROD TOOLS ARE : &&TOT_REM   ";
PUT ' ';
PUT "The below mentioned are the list of tools removed from TSPROD";
PUT ' ';
PUT "&&REM_TOL";
PUT ' ';
PUT ' ';
PUT 'Thanks,';
PUT "Orion";
RUN;


         %LOOP2;

   %MEND;


    %MACRO NEW;

      %IF &&TOT_NEW>0 OR &&TOT_REM>0  %THEN %DO;
         %MYMAC1;

      %END;
  %MEND;

   %NEW;
ENDSAS;
%/RELEASE EXEC PGM=RELJOB,PARM=&$USERID.FNL
%ENDS
