%LET JOBID=FNL,GO=YES
%CREATE 1,1
%JCLSETUP: %CREATE 1,1
%PARSE   DATE,&$DATE
%LET YY=&$1
%LET MM=&$2
%LET DD=&$3
%LET SDATE=&YY-&MM-&DD
%WRITE SDATE=&YY-&MM-&DD
%LET TR1=20
%LET TRY=&TR1&SDATE
%/&$USERID.&JOBID JOB 1910-0000-1000,TIME=(0,15),REGION=6M,TYPRUN=HOLD,
%/    MSGLEVEL=(1,1),MSGCLASS=R,NOTIFY=&$USERID
%*JOBPARM LINES=999
%/*
%/MAKE EXEC GUTSUTIL,CONTROL='$'
%/SYSPUNCH DD DSN=&&TEMPL,
%/      DCB=(LRECL=240,BLKSIZE=23280,RECFM=FB),
%/       SPACE=(TRK,(10,10),RLSE),
%/      UNIT=SYSSQ,DISP=(NEW,PASS,DELETE)
%/SYSIN DD *
$PUNCH  MSZHZ.TSPRODLT
%/*
%/SAS   EXEC SAS,OPTIONS='EMAILHOST=SMTP.INFORES.COM',
%/      WORK='990,800',REGION=6M
%/FT22F001 DD   SYSOUT=*
%/CNGLIST  DD SYSOUT=(F,&$USERID),DEST=GUTS,DSN=&&CNGLIST
%/NEWLIST DD DSN=&&TEMPL,DISP=(OLD,DELETE)
%/*
%/SYSOUT   DD DUMMY
%/SYSIN    DD *
%SET        TEMPORARY,NOCOMMAND

OPTIONS NOCENTER NODATE;

DATA DATE2DAY;
 INFILE CARDS;
 INPUT DDATE1 YYMMDD10.;
 CARDS;
&TRY
;
RUN;

DATA DATE2DAY;
 SET DATE2DAY;
 MONTH=TRIM(LEFT(PUT(DDATE1,MONNAME.)));
 MONTH1=SUBSTR(MONTH,1,3);
 DATESTRING=PUT(DAY(DDATE1),Z2.)||"-"||
            TRIM(MONTH1)||"-"||
            PUT(DDATE1,YEAR4.);
KEEP DATESTRING DDATE1;
RUN;

PROC SQL NOPRINT;
 SELECT DATESTRING INTO: TRY1 FROM DATE2DAY;
QUIT;

DATA NEWLIST NEWLISTT;
 INFILE  NEWLIST FIRSTOBS=3;
  M=TODAY();
 INPUT
  NAME :$16.
  @20 DESCRIP $50.
  SIZE
  CREATED :$10.
  UPDATED :$10.
  EXPRIES $
  LSTUSED :$10.
  LINES
  PROT    $
  OWNER :$5.;
  CUTOFF=M-7;  /* CUT OFF DATE FOR THE WEEKS-CURRENTLY 3 WEEKS */
TODATE=M;
RUN ;

DATA NEWLIST;
SET NEWLIST;
 K=INPUT(CREATED,YYMMDD10.);
 IF UPDATED¬='0000-00-00'  THEN DO;
   L=INPUT(UPDATED,YYMMDD10.);
 END;
RUN;



PROC PRINT DATA=NEWLIST (OBS=1) UNIFORM;
 WHERE OWNER NOT IN ('MSVID','MSCHG','TSJES','MSCES');
 *ITLE   '********************* REPORT *************************';
 *OOTNOTE   '********************* ***************************';
 VAR NAME OWNER CREATED UPDATED;

PROC SQL NOPRINT;
SELECT DISTINCT(TODATE) INTO:TODATE FROM NEWLIST;
SELECT DISTINCT(CUTOFF) INTO:CUTOFF FROM NEWLIST;
CREATE TABLE REPORT1 AS
 SELECT OWNER,COUNT(*) AS TOTAL_TOOLS FROM NEWLIST GROUP BY OWNER
 ORDER BY TOTAL_TOOLS ;
QUIT;

*ROC PRINT DATA=REPORT1;
 TITLE ' '; FOOTNOTE ' ';
*UN;

 PROC PRINT DATA=NEWLIST;
 WHERE UPDATED='0000-00-00';
DATA NEWLIST1;
 SET NEWLIST;
 IF UPDATED¬='0000-00-00';
 IF L GT &&CUTOFF;

PROC SQL;
CREATE TABLE REPORT2 AS
 SELECT OWNER,COUNT(*) AS TOTAL_TOOLS FROM NEWLIST1 GROUP BY OWNER
 ORDER BY TOTAL_TOOLS ;
QUIT;



                    /*  CONCATENATING RECORDS  */

DATA REPORTT (KEEP=LIST);
 LENGTH LIST $20.;
 SET REPORT2;
 LIST=OWNER||"  "||TOTAL_TOOLS;
IF OWNER IN ('MSVID','MSCHG','TSJES','MSCES') THEN DELETE;
RUN;


DATA NEWLISTT(RENAME = (DATESTRING1=CREATED DATESTRING2=UPDATED));
SET NEWLISTT;
 K=INPUT(CREATED,YYMMDD10.);
 IF UPDATED ='0000-00-00'  THEN DELETE;
 L=INPUT(UPDATED,YYMMDD10.);
 IF L GT &&CUTOFF;
 FNL= NAME||OWNER||CREATED||UPDATED;
MONTH1=TRIM(LEFT(PUT(K,MONNAME.)));
MONTH2=SUBSTR(MONTH1,1,3);
DATESTRING1=PUT(DAY(K),Z2.)||"-"||
           TRIM(MONTH2)||"-"||
           PUT(K,YEAR4.);
MONTH3=TRIM(LEFT(PUT(L,MONNAME.)));
MONTH4=SUBSTR(MONTH3,1,3);
DATESTRING2=PUT(DAY(L),Z2.)||"-"||
           TRIM(MONTH4)||"-"||
           PUT(L,YEAR4.);
DROP MONTH1 MONTH2 MONTH3 MONTH4 UPDATED CREATED;
RUN;

DATA CNGLIST      (KEEP=ACG);
 SET NEWLISTT;
  PART1="%"||"TSCOMP TSPROD."||SUBSTR(NAME,8,8);
  PART2=","||"TSCONT."||SUBSTR(NAME,8,8);
  ACG=TRIM(PART1)||TRIM(PART2);
RUN;

DATA _NULL_;
  FILE CNGLIST NOTITLE;
  SET CNGLIST;
  PUT
  @1 ACG $45.;
RUN;

DATA NEWLIST9 (DROP=NAME OWNER CREATED UPDATED);
  LENGTH    NAME1 $16. OWNER1 $8. CREATED1 $14.  UPDATED1 $14. ;
  LENGTH   FNL $55.;
 SET NEWLISTT;
  NAME1=NAME;
  OWNER1=OWNER;
  CREATED1=CREATED;
  UPDATED1=UPDATED ;
  FNL= NAME1||"  "||OWNER1||CREATED1||UPDATED1;
RUN;

PROC PRINT DATA=NEWLIST9 (OBS=2) UNIFORM;
PROC PRINT DATA=REPORTT  (OBS=9) ;

PROC SORT; BY NAME1;

PROC SQL NOPRINT;
 CREATE TABLE ROW_NUM AS
  SELECT *,MONOTONIC() AS ROW_NUM
  FROM NEWLIST9
;
 CREATE TABLE OWNER_NUM AS
  SELECT *,MONOTONIC() AS ROW_NUM
  FROM REPORTT
;
QUIT;


PROC PRINT DATA=ROW_NUM;
 TITLE 'NEW TEST RUN';
 VAR ROW_NUM FNL;
RUN;

PROC SORT DATA=NEWLIST9;
 BY OWNER1;
RUN;


PROC SQL NOPRINT;
 SELECT COUNT(*) INTO:CHK  FROM NEWLIST9;
 SELECT COUNT(*) INTO:CHK2 FROM REPORTT;
QUIT;

    %MACRO GEN_MAC;
     %DO I=1 %TO &&CHK;

  DATA NEW;
   SET NEWLIST9 (FIRSTOBS=&&I OBS=&&I );
  RUN;

  PROC SQL NOPRINT;
    SELECT FNL INTO:TARG&&I FROM NEW;
  QUIT;

    %END;
     %DO I=1 %TO &&CHK2;

  DATA REP01;
   SET REPORTT  (FIRSTOBS=&&I OBS=&&I );
  RUN;

  PROC SQL ;  *NOPRINT;
    SELECT LIST INTO:LIST&&I FROM REP01;
  QUIT;

    %END;
    %IF &&CHK<25 %THEN %DO;
     %DO I=25 %TO &&CHK;
       %LET TARG&&I=' ';
     %END;
    %END;

     %MACRO VKYMAC1;
       %LET TOLIST="Orion.Zhao@iriworldwide.com";
          FILENAME MYMAIL EMAIL TO=(&&TOLIST)

           SUBJECT="DIRECTORY UPDATED MAIL --> PHASE III ";
DATA _NULL_;
  FILE MYMAIL;
PUT 'Hi, ';
PUT ' ';
PUT ' The below is the weekly report status of updated tools    ';
PUT " TSPROD Directory as on  &&TRY1 ";
PUT ' ';
PUT ' ';
PUT "Number of updated TSPROD tools are : &&CHK       ";
PUT "=================================================";
PUT "  TOOLNAME     UPDATED_BY  CREATED_ON MODIFIED_ON";
PUT "=================================================";
PUT ' ';
       %DO I=1 %TO &&CHK;
 PUT "&&&&TARG&&I ";
    %END;
PUT ' ';
PUT ' ';
PUT "TSPROD tool count by Owner-wise    ";
PUT "  OWNER   NO. OF TOOLS UPDATED";
PUT "========================";
       %DO I=1 %TO &&CHK2;
 PUT "&&&&LIST&&I ";
    %END;
PUT ' ';
PUT 'Thanks,';
PUT "Orion";
RUN;

   %MEND;
    %VKYMAC1;

   %MEND;
  %GEN_MAC;





ENDSAS;
%/*
%IFNONE  N-NO=YES %PERFORM %ENDSUBMIT
